// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3gQ1pVId8HlgIZ1NttvjWs_Dhkv5hc_w',
    appId: '1:394399749102:web:24434c64ae508b613534ff',
    messagingSenderId: '394399749102',
    projectId: 'notes-app-e1594',
    authDomain: 'notes-app-e1594.firebaseapp.com',
    storageBucket: 'notes-app-e1594.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9yjz3pfijSd5LWl59-MpzopjZl_hbvRM',
    appId: '1:394399749102:android:462a98a74077fead3534ff',
    messagingSenderId: '394399749102',
    projectId: 'notes-app-e1594',
    storageBucket: 'notes-app-e1594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4b7xF4Gcig56XhsS7qMs9S7B8MEuj3AU',
    appId: '1:394399749102:ios:e92af0bd3be6309c3534ff',
    messagingSenderId: '394399749102',
    projectId: 'notes-app-e1594',
    storageBucket: 'notes-app-e1594.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4b7xF4Gcig56XhsS7qMs9S7B8MEuj3AU',
    appId: '1:394399749102:ios:e92af0bd3be6309c3534ff',
    messagingSenderId: '394399749102',
    projectId: 'notes-app-e1594',
    storageBucket: 'notes-app-e1594.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3gQ1pVId8HlgIZ1NttvjWs_Dhkv5hc_w',
    appId: '1:394399749102:web:8732b210777417123534ff',
    messagingSenderId: '394399749102',
    projectId: 'notes-app-e1594',
    authDomain: 'notes-app-e1594.firebaseapp.com',
    storageBucket: 'notes-app-e1594.firebasestorage.app',
  );
}
